# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6bb8676da68c383a2b44f6f1e520e470b3f9c3c0680e86e9f09e315c1bdded0b164dc1011f6e8b913bf64af9af34e8adff1363e346672f1474d40891abb073e

test:
  secret_key_base: 9fa4b9f54d9dbc7ca985e46b61bbc99f8518b9479e69fe3e2f64d49df2fd30cff04951c09a8a54c3d33cc393c4ea3a39de3ad6facc257bb3a7b7379b547cc98c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
